### ISSUE TITLE
error finding cv.h

### ISSUE THREAD

**Issue by sasadep** [clementfarabet/lua---camera#20]
Anytime I try to do `luarocks install camera`, I get this following error:

```
Scanning dependencies of target camopencv
[ 25%] Building C object opencv/CMakeFiles/camopencv.dir/opencv.c.o
/tmp/luarocks_camera-1.1-0-18/lua---camera/opencv/opencv.c:29:16: fatal error: cv.h: No such file or directory
 #include <cv.h>
                ^
compilation terminated.
make[2]: *** [opencv/CMakeFiles/camopencv.dir/opencv.c.o] Error 1
make[1]: *** [opencv/CMakeFiles/camopencv.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
```

I also have opencv 3.0.0 installed on Ubuntu 14.04 LTS.

**Comment by karandwivedi42** [comment]
@sasadep How did you solve this?

**Comment by soumith** [comment]
@karandwivedi42 you might have opencv 3.0 installed. This package is for opencv 2.4xx

There's separate camera bindings for opencv 3.0 here: https://github.com/VisionLabs/torch-opencv with examples here: https://github.com/VisionLabs/torch-opencv/tree/master/demo

**Comment by karandwivedi42** [comment]
Thanks.

I was not able to install torch-opencv too though. The issue is with the
modules moved to opencv_contrib i guess.
ᐧ

**Comment by johnny5550822** [comment]
@karandwivedi42 Did you solve the problem? Do I need to install opencv2.4x instead of 3.0x?

**Comment by karandwivedi42** [comment]
Not sure about lua-camera, but opencv-torch worked for me:

https://github.com/VisionLabs/torch-opencv/issues/50
